# Generated by Django 5.0.7 on 2025-12-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting', models.BigIntegerField(db_index=True, unique=True, verbose_name='Cutting Number')),
                ('zr', models.CharField(blank=True, max_length=20, null=True)),
                ('order_type', models.CharField(blank=True, max_length=10, null=True)),
                ('contenedor', models.CharField(blank=True, max_length=30, null=True)),
                ('swo', models.BigIntegerField(blank=True, null=True)),
                ('aging_days', models.PositiveIntegerField(blank=True, null=True)),
                ('cb', models.CharField(max_length=30)),
                ('item', models.BigIntegerField()),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('location', models.CharField(db_index=True, max_length=20)),
                ('units', models.PositiveIntegerField()),
                ('style', models.CharField(blank=True, max_length=30, null=True)),
                ('swo_style', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('source_report', models.CharField(help_text='Reporte que originó el último update', max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Inventory',
                'verbose_name_plural': 'Global Inventories',
                'db_table': 'global_inventory',
            },
        ),
    ]
