# Generated by Django 5.0.7 on 2025-12-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting', models.BigIntegerField(db_index=True)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_location', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_units', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_contenedor', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('new_location', models.CharField(max_length=20)),
                ('new_units', models.PositiveIntegerField()),
                ('new_contenedor', models.CharField(blank=True, max_length=30, null=True)),
                ('source_report', models.CharField(max_length=30)),
                ('event_type', models.CharField(help_text='TRANSITO→YARDA, YARDA→RECEIVING, UNIT_CHANGE, etc.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
