# Generated by Django 6.0 on 2026-01-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinventory',
            name='item',
            field=models.CharField(max_length=30),
        ),
    ]
